### PR TITLE
fixup osx 3.8 build.

### PR DESCRIPTION
**Pull request by hmaarrfk**
closes
https://github.com/cython/cython/issues/3248

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@cython I'm not sure why you need to update to the devel branch. I think we are there on scikit-image. I guess the devel branch isn't super well tested??? but anyway, seems to work. I'm now trying to backtrack on the updated versions of xcode I used.

**Comment by hmaarrfk** [comment]
I think the one failure can be restarted right?

**Comment by mattip** [comment]
The devel branch is actually the better tested branch of that repo. The master branch should be updated from devel, but in practice it is far behind the devel one.

**Comment by hmaarrfk** [comment]
Git Sigh, I can't even understand how to rebase this change.

At scikit-image, we finally decided to move away from git submodules and directly clone the repos we need.

Would that "solution" be considered in cython?
https://github.com/scikit-image/scikit-image-wheels/pull/35

**Comment by mattip** [comment]
@hmaarrfk Would you like help getting multibuild to the HEAD of devel? I think I can force push to your branch, or I could open a new PR

**Comment by scoder** [comment]
I got things to work in the master branch:
https://travis-ci.org/MacPython/cython-wheels/builds/648406238
It fails for Py3.4/5 on macs now, but I can totally live with that. I'll just disable those and hope that people don't really use them that much any more, at least on MacOS.

The Windows builds are still in a bit of a sad state, but that's a different issue.
I'll close this PR as outdated, but it helped me try out a couple of things, so: thanks!

**Comment by scoder** [comment]
Regarding moving away from the submodules, I don't think it's worth putting effort into this. Upgrading those is currently trivial, the main work is to find a version that works whenever things break for whatever reason (usually a new Python release), and keeping the config working on upgrades. But that doesn't happen very often.

**Pull request closed without merging**
